# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lgobbmoymGju31D03p_o78zTfsnN-Kb2
"""

!pip install pyrosm
!pip install shapely==1.8.5

# Read POIs such as amenities and shops
# =====================================
from pyrosm import OSM
from pyrosm import get_data
fp = get_data("dublin")
# Initialize the OSM parser object
osm = OSM(fp)

nodes, edges = osm.get_network(nodes=True)
edges.head()

# !pip3 install networkx==2.3 
# import networkx as nx
nodes, edges = osm.get_network(network_type="driving", nodes=True)

!pip install pandana

G = osm.to_graph(nodes, edges, graph_type="pandana")



parks = osm.get_pois(custom_filter={"leisure": ["park"]})
parks["geometry"] = parks.centroid
parks = parks.dropna(subset=["lon", "lat"])
G.precompute(1000)
G.set_pois(category="parks", maxdist=1000, maxitems=10, 
           x_col=parks.lon, y_col=parks.lat)

nearest_five = G.nearest_pois(1000, "parks", num_pois=5)
nearest_five.tail(10)

nearest_five.head()

# Get test data 
fp = get_data("dublin")

# Initialize the reader
osm = OSM(fp)

# Read POIs with custom filter B
my_filter={"amenity": ["school"], "leisure": ["park"]}
pois = osm.get_pois(custom_filter=my_filter)

# Merge poi type information into a single column
# pois["shop"] = pois["shop"].fillna(' ')
pois["amenity"] = pois["amenity"].fillna(' ')
pois["leisure"] = pois["leisure"].fillna(' ')
# pois["tourism"] = pois["tourism"].fillna(' ')
pois["poi_type"] = pois["amenity"] + pois["leisure"] 

# Plot
ax = pois.plot(column="poi_type", legend=True, markersize=1, figsize=(14,8), legend_kwds=dict(loc='upper left', ncol=6, bbox_to_anchor=(1, 1)))

type(pois)

pois.to_file('school_parks.geojson', driver='GeoJSON')

